"""add description

Revision ID: dd791e3a1259
Revises: 
Create Date: 2024-01-06 18:08:55.116964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd791e3a1259'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_category_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_course_category_model_id'), 'course_category_model', ['id'], unique=False)
    op.create_table('teacher_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_model_id'), 'teacher_model', ['id'], unique=False)
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interested_categories', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_model_id'), 'user_model', ['id'], unique=False)
    op.create_table('course_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technologicals', sa.Text(), nullable=True),
    sa.Column('course_views', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['course_category_model.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_course_model_id'), 'course_model', ['id'], unique=False)
    op.create_table('chapter_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_model_id'), 'chapter_model', ['id'], unique=False)
    op.create_table('course_enroll_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('student', sa.Integer(), nullable=True),
    sa.Column('enrolled_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course_model.id'], ),
    sa.ForeignKeyConstraint(['student'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_enroll_model_enrolled_time'), 'course_enroll_model', ['enrolled_time'], unique=False)
    op.create_index(op.f('ix_course_enroll_model_id'), 'course_enroll_model', ['id'], unique=False)
    op.create_table('module_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chapter'], ['chapter_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course'], ['course_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_model_id'), 'module_model', ['id'], unique=False)
    op.create_table('stage_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('module', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module'], ['module_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_model_id'), 'stage_model', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_model_id'), table_name='stage_model')
    op.drop_table('stage_model')
    op.drop_index(op.f('ix_module_model_id'), table_name='module_model')
    op.drop_table('module_model')
    op.drop_index(op.f('ix_course_enroll_model_id'), table_name='course_enroll_model')
    op.drop_index(op.f('ix_course_enroll_model_enrolled_time'), table_name='course_enroll_model')
    op.drop_table('course_enroll_model')
    op.drop_index(op.f('ix_chapter_model_id'), table_name='chapter_model')
    op.drop_table('chapter_model')
    op.drop_index(op.f('ix_course_model_id'), table_name='course_model')
    op.drop_table('course_model')
    op.drop_index(op.f('ix_user_model_id'), table_name='user_model')
    op.drop_table('user_model')
    op.drop_index(op.f('ix_teacher_model_id'), table_name='teacher_model')
    op.drop_table('teacher_model')
    op.drop_index(op.f('ix_course_category_model_id'), table_name='course_category_model')
    op.drop_table('course_category_model')
    # ### end Alembic commands ###
